server:
  port: 8081
  tomcat:
    max-http-post-size: -1
spring:
  redis:
    host: ${YPAT_REDIS_HOST:localhost}
    port: ${YPAT_REDIS_PORT:6379}
    password: ${YPAT_REDIS_PASSWORD:}
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  jackson:
    time-zone: GMT+8
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true


##FeignClient超时设置
---
spring.cloud.loadbalancer.retry.enabled: false
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon.ConnectTimeout: 250
ribbon.ReadTimeout: 5000
ribbon.OkToRetryOnAllOperations: false
ribbon.MaxAutoRetriesNextServer: 0
ribbon.MaxAutoRetries: 0
