#FastDFS配置begin-----------
fastdfs.connect_timeout_in_seconds = 10
fastdfs.network_timeout_in_seconds = 30
fastdfs.charset = UTF-8
fastdfs.http_anti_steal_token = false
fastdfs.http_secret_key =
fastdfs.http_tracker_http_port = 8888

# 开发: 共享 ypat_ypat-net 网络,容器名直接访问
fastdfs.tracker_servers = ypat-fastdfs-tracker:22122
#FastDFS配置end-----------