CREATE TABLE IF NOT EXISTS t_message_push_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  event_type VARCHAR(32) NOT NULL,
  business_type VARCHAR(32) DEFAULT NULL,
  message_id BIGINT DEFAULT NULL,
  ypatid BIGINT DEFAULT NULL,
  sendperid BIGINT DEFAULT NULL,
  recperid BIGINT DEFAULT NULL,
  touser_openid VARCHAR(128) DEFAULT NULL,
  template_id VARCHAR(128) DEFAULT NULL,
  page_url VARCHAR(255) DEFAULT NULL,
  success VARCHAR(8) DEFAULT NULL,
  wechat_errcode VARCHAR(32) DEFAULT NULL,
  wechat_errmsg VARCHAR(255) DEFAULT NULL,
  response_body VARCHAR(1024) DEFAULT NULL,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_message_push_log_created_at (created_at),
  KEY idx_message_push_log_message_id (message_id),
  KEY idx_message_push_log_ypatid (ypatid),
  KEY idx_message_push_log_openid (touser_openid),
  KEY idx_message_push_log_result (event_type, business_type, success)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
